"""
WAF 检测技能
检测 Web 应用防火墙和入侵防御系统的存在，识别 WAF 类型并提供绕过建议
"""
import json
import os
import re
import sys
import time
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import urljoin, urlparse

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry


# WAF 签名数据库
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": [
            "cf-ray",
            "cf-cache-status",
            "cf-request-id",
            "__cfduid",
        ],
        "cookies": [
            "__cfduid",
            "cf_clearance",
            "__cf_bm",
        ],
        "response_patterns": [
            "Cloudflare",
            "cf-error",
            "cf-chl",
            "Attention Required! | Cloudflare",
        ],
        "status_codes": [403, 503],
    },
    "AWS WAF": {
        "headers": [
            "x-amzn-requestid",
            "x-amz-cf-id",
            "x-amz-cf-pop",
        ],
        "cookies": [
            "aws-waf-token",
        ],
        "response_patterns": [
            "Request blocked",
            "AWS WAF",
            "Request ID:",
        ],
        "status_codes": [403],
    },
    "ModSecurity": {
        "headers": [
            "x-modsecurity",
        ],
        "cookies": [],
        "response_patterns": [
            "ModSecurity",
            "This error was generated by Mod_Security",
            "mod_security",
            "Not Acceptable",
        ],
        "status_codes": [403, 406],
    },
    "F5 BIG-IP ASM": {
        "headers": [
            "x-wa-info",
            "x-cnection",
        ],
        "cookies": [
            "TS[0-9a-f]{6}",
            "F5_ST",
            "BIGipServer",
            "LastMRH_Session",
            "MRHSession",
        ],
        "response_patterns": [
            "The requested URL was rejected",
            "F5 Networks",
            "BIG-IP",
        ],
        "status_codes": [403],
    },
    "Imperva / Incapsula": {
        "headers": [
            "x-iinfo",
            "x-cdn",
            "x-cdn-request-id",
        ],
        "cookies": [
            "incap_ses_",
            "visid_incap_",
            "_incap_",
            "nlbi_",
        ],
        "response_patterns": [
            "Incapsula",
            "incap_ses",
            "visid_incap",
            "_Incapsula_Resource",
        ],
        "status_codes": [403],
    },
    "Akamai": {
        "headers": [
            "x-akamai-transformed",
            "x-akamai-request-id",
            "akamai-origin-hop",
        ],
        "cookies": [],
        "response_patterns": [
            "Akamai",
            "Reference #",
            "access.denied",
        ],
        "status_codes": [403],
    },
    "Sucuri": {
        "headers": [
            "x-sucuri-id",
            "x-sucuri-cache",
        ],
        "cookies": [
            "sucuri_cloudproxy_uuid",
            "sucuri",
        ],
        "response_patterns": [
            "Sucuri WebSite Firewall",
            "Access Denied - Sucuri Website Firewall",
            "sucuri",
        ],
        "status_codes": [403],
    },
    "Barracuda": {
        "headers": [],
        "cookies": [
            "barra_counter_session",
            "BNI__BARRACUDA_LB_COOKIE",
            "BNI_persistence",
        ],
        "response_patterns": [
            "Barracuda",
            "barracuda",
        ],
        "status_codes": [403],
    },
    "FortiWeb": {
        "headers": [
            "x-fw-",
            "fortigate",
        ],
        "cookies": [
            "FORTIWAFSID",
        ],
        "response_patterns": [
            "FortiWeb",
            "Application Firewall",
        ],
        "status_codes": [403],
    },
    "Wordfence (WordPress)": {
        "headers": [
            "x-wordfence",
        ],
        "cookies": [],
        "response_patterns": [
            "Generated by Wordfence",
            "Your access to this site has been limited",
            "Wordfence",
        ],
        "status_codes": [403, 503],
    },
    "Cloudbric": {
        "headers": [],
        "cookies": [
            "Cloudbric",
        ],
        "response_patterns": [
            "Cloudbric",
        ],
        "status_codes": [403],
    },
    "Wallarm": {
        "headers": [
            "x-wallarm",
        ],
        "cookies": [],
        "response_patterns": [
            "Wallarm",
        ],
        "status_codes": [403],
    },
    "阿里云 WAF": {
        "headers": [
            "x-waf-",
            "aliyun",
        ],
        "cookies": [
            "aliyungf_tc",
        ],
        "response_patterns": [
            "阿里云",
            "Aliyun",
            "WAF",
        ],
        "status_codes": [403, 405],
    },
    "腾讯云 WAF": {
        "headers": [
            "x-tencent",
            "tencent",
        ],
        "cookies": [],
        "response_patterns": [
            "腾讯云",
            "Tencent",
            "WAF",
        ],
        "status_codes": [403],
    },
    "长亭 SafeLine": {
        "headers": [
            "x-safeline",
            "safeline",
        ],
        "cookies": [
            "safeline",
        ],
        "response_patterns": [
            "SafeLine",
            "长亭",
            "雷池",
        ],
        "status_codes": [403],
    },
}

# 绕过建议
BYPASS_SUGGESTIONS = {
    "Cloudflare": [
        {
            "technique": "HTTP 请求走私",
            "description": "利用 HTTP 请求走私漏洞绕过 Cloudflare 检测",
            "difficulty": "hard",
        },
        {
            "technique": "WebSocket 连接",
            "description": "通过 WebSocket 连接绕过某些防护规则",
            "difficulty": "medium",
        },
        {
            "technique": "大文件分块传输",
            "description": "使用分块传输编码发送大文件，触发检查限制",
            "difficulty": "medium",
        },
    ],
    "AWS WAF": [
        {
            "technique": "HTTP 参数污染",
            "description": "发送重复参数，利用解析差异绕过规则",
            "difficulty": "medium",
        },
        {
            "technique": "Unicode 编码",
            "description": "使用 Unicode 编码变体绕过模式匹配",
            "difficulty": "easy",
        },
        {
            "technique": "大小写混用",
            "description": "对 SQL/HTML 关键字使用大小写混用绕过检测",
            "difficulty": "easy",
        },
    ],
    "ModSecurity": [
        {
            "technique": "多部分表单绕过",
            "description": "利用 multipart/form-data 解析漏洞绕过检测",
            "difficulty": "medium",
        },
        {
            "technique": "空字节注入",
            "description": "在 payload 中插入空字节截断规则匹配",
            "difficulty": "easy",
        },
        {
            "technique": "注释混淆",
            "description": "在 SQL 关键字中使用内联注释混淆",
            "difficulty": "easy",
        },
    ],
    "F5 BIG-IP ASM": [
        {
            "technique": "路径规范化",
            "description": "利用路径规范化差异绕过 URL 过滤",
            "difficulty": "medium",
        },
        {
            "technique": "编码绕过",
            "description": "使用双重 URL 编码绕过参数过滤",
            "difficulty": "easy",
        },
    ],
    "Imperva / Incapsula": [
        {
            "technique": "HTTP 方法覆盖",
            "description": "使用 X-HTTP-Method-Override 头修改请求方法",
            "difficulty": "medium",
        },
        {
            "technique": "内容类型欺骗",
            "description": "修改 Content-Type 头绕过请求体检查",
            "difficulty": "easy",
        },
    ],
    "阿里云 WAF": [
        {
            "technique": "编码绕过",
            "description": "使用多种编码方式混合绕过检测",
            "difficulty": "medium",
        },
        {
            "technique": "分块绕过",
            "description": "将恶意 payload 分拆到多个参数中",
            "difficulty": "medium",
        },
    ],
    "腾讯云 WAF": [
        {
            "technique": "请求方法变换",
            "description": "使用不常见的 HTTP 方法绕过检测",
            "difficulty": "easy",
        },
        {
            "technique": "参数位置变换",
            "description": "将参数从 URL 移到请求体或 Cookie 中",
            "difficulty": "easy",
        },
    ],
    "default": [
        {
            "technique": "编码绕过",
            "description": "使用 URL 编码、Unicode 编码等方式绕过模式匹配",
            "difficulty": "easy",
        },
        {
            "technique": "大小写混用",
            "description": "对关键字使用大小写变体绕过基于字符串的检测",
            "difficulty": "easy",
        },
        {
            "technique": "分块传输编码",
            "description": "使用 Transfer-Encoding: chunked 分片发送 payload",
            "difficulty": "medium",
        },
        {
            "technique": "HTTP 参数污染",
            "description": "发送重复参数利用 WAF 和后端解析差异",
            "difficulty": "medium",
        },
        {
            "technique": "空字节注入",
            "description": "在 payload 中插入空字节 (%00) 截断 WAF 检测",
            "difficulty": "easy",
        },
    ],
}


class WAFDetector:
    """WAF 检测器"""

    # 测试 payload - 用于触发 WAF
    TEST_PAYLOADS = [
        "/?id=1' OR '1'='1",
        "/?id=1 UNION SELECT 1,2,3",
        "/?q=<script>alert(1)</script>",
        "/?file=../../etc/passwd",
        "/?cmd=cat /etc/passwd",
        "/?exec=id",
        "/etc/passwd",
        "/.env",
        "/wp-admin",
        "/phpmyadmin",
    ]

    def __init__(self, config: Dict[str, Any]):
        self.target_url = config["target_url"].rstrip("/")
        self.test_payloads = config.get("test_payloads", []) or self.TEST_PAYLOADS
        self.timeout = config.get("timeout", 10)
        self.headers = config.get("headers", {})
        self.proxy = config.get("proxy")

        self.waf_detected = False
        self.waf_type = ""
        self.waf_name = ""
        self.confidence = "low"
        self.matched_signatures: List[str] = []
        self.response_headers: Dict[str, str] = {}
        self.block_page_analysis = ""

    def _create_session(self) -> requests.Session:
        """创建 HTTP 会话"""
        session = requests.Session()

        retry_strategy = Retry(total=1, backoff_factor=0.3, status_forcelist=[429])
        adapter = HTTPAdapter(max_retries=retry_strategy)
        session.mount("http://", adapter)
        session.mount("https://", adapter)

        default_headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
        }
        session.headers.update(default_headers)

        if self.headers:
            session.headers.update(self.headers)
        if self.proxy:
            session.proxies = {"http": self.proxy, "https": self.proxy}

        return session

    def _detect_by_headers(self, resp: requests.Response) -> List[str]:
        """通过响应头检测 WAF"""
        signatures = []

        for waf_name, waf_data in WAF_SIGNATURES.items():
            # 检查响应头
            for header_pattern in waf_data.get("headers", []):
                for header_name, header_value in resp.headers.items():
                    if header_pattern.lower() in header_name.lower():
                        signatures.append(
                            f"{waf_name}: 响应头 {header_name}"
                        )
                        break

            # 检查 Set-Cookie
            set_cookie = resp.headers.get("Set-Cookie", "")
            for cookie_pattern in waf_data.get("cookies", []):
                if re.search(cookie_pattern, set_cookie, re.IGNORECASE):
                    signatures.append(
                        f"{waf_name}: Cookie 匹配 {cookie_pattern}"
                    )
                    break

        return signatures

    def _detect_by_response(self, resp: requests.Response) -> List[str]:
        """通过响应内容检测 WAF"""
        signatures = []

        for waf_name, waf_data in WAF_SIGNATURES.items():
            for pattern in waf_data.get("response_patterns", []):
                if re.search(pattern, resp.text, re.IGNORECASE):
                    signatures.append(
                        f"{waf_name}: 响应内容匹配 '{pattern}'"
                    )
                    break

        return signatures

    def _detect_by_status(self, resp: requests.Response) -> List[str]:
        """通过状态码检测 WAF"""
        signatures = []

        for waf_name, waf_data in WAF_SIGNATURES.items():
            if resp.status_code in waf_data.get("status_codes", []):
                # 状态码本身不够，需要结合其他特征
                pass

        return signatures

    def _analyze_block_page(self, resp: requests.Response) -> str:
        """分析拦截页面特征"""
        indicators = []

        text = resp.text.lower()

        # 常见拦截页面关键词
        block_keywords = [
            "blocked", "block", "denied", "deny", "forbidden",
            "access denied", "not allowed", "request rejected",
            "your request has been", "request has been blocked",
            "security policy", "security rules", "firewall",
            "waf", "web application firewall",
            "challenge", "captcha", "verify",
            "ddos", "rate limit", "too many requests",
            "ip address has been", "your ip",
            "attention required", "please enable javascript",
            "checking your browser", "browser check",
            "被拦截", "访问被拒绝", "请求被拒绝",
            "安全策略", "防火墙", "访问控制",
            "非法请求", "恶意请求",
        ]

        for keyword in block_keywords:
            if keyword in text:
                indicators.append(keyword)

        if indicators:
            return f"拦截页面包含关键词: {', '.join(indicators[:5])}"

        # 检查响应长度
        if len(resp.text) < 500 and resp.status_code in (403, 406, 501, 503):
            return f"短响应页面 ({len(resp.text)} 字节), 状态码 {resp.status_code}"

        return ""

    def _identify_waf(self, all_signatures: List[str]) -> Tuple[str, str, str]:
        """根据签名识别 WAF 类型"""
        if not all_signatures:
            return "", "", "low"

        # 统计每个 WAF 的匹配次数
        waf_matches: Dict[str, int] = {}
        for sig in all_signatures:
            waf_name = sig.split(":")[0]
            waf_matches[waf_name] = waf_matches.get(waf_name, 0) + 1

        # 找到匹配最多的 WAF
        best_match = max(waf_matches, key=waf_matches.get)
        best_count = waf_matches[best_match]

        if best_count >= 3:
            confidence = "high"
        elif best_count >= 2:
            confidence = "medium"
        else:
            confidence = "low"

        return best_match, best_match, confidence

    def _get_bypass_suggestions(self, waf_name: str) -> List[Dict[str, str]]:
        """获取 WAF 绕过建议"""
        suggestions = BYPASS_SUGGESTIONS.get(
            waf_name, BYPASS_SUGGESTIONS["default"]
        )

        # 如果是低置信度，添加通用建议
        if self.confidence == "low":
            generic = BYPASS_SUGGESTIONS["default"]
            # 合并去重
            seen = {s["technique"] for s in suggestions}
            for s in generic:
                if s["technique"] not in seen:
                    suggestions.append(s)

        return suggestions

    def detect(self) -> Dict[str, Any]:
        """执行 WAF 检测"""
        start_time = time.time()

        print(f"[信息] 目标: {self.target_url}")

        session = self._create_session()

        all_signatures = []
        block_page_found = False
        tests_performed = 0

        # 1. 先发送正常请求获取基线
        try:
            normal_resp = session.get(
                self.target_url, timeout=self.timeout, allow_redirects=True
            )
            print(f"[基线] 状态码: {normal_resp.status_code}, 大小: {len(normal_resp.text)} 字节")

            # 检测正常响应的头信息
            header_sigs = self._detect_by_headers(normal_resp)
            all_signatures.extend(header_sigs)

        except Exception as e:
            print(f"[错误] 无法访问目标: {e}")
            return {
                "waf_detected": False,
                "waf_type": "",
                "waf_name": "",
                "confidence": "low",
                "details": {
                    "detection_method": "connection_failed",
                    "matched_signatures": [],
                    "response_headers": {},
                    "block_page_analysis": f"无法连接到目标: {e}",
                },
                "bypass_suggestions": [],
                "summary": {
                    "tests_performed": 0,
                    "waf_detected": False,
                    "duration_seconds": round(time.time() - start_time, 2),
                },
            }

        # 2. 发送恶意 payload 测试 WAF
        print(f"[信息] 发送 {len(self.test_payloads)} 个测试 payload...")

        for payload in self.test_payloads:
            tests_performed += 1
            test_url = urljoin(self.target_url, payload)

            try:
                resp = session.get(
                    test_url, timeout=self.timeout, allow_redirects=False
                )

                # 检查是否被拦截
                if resp.status_code in (403, 406, 429, 501, 503):
                    # 检测拦截页面特征
                    block_analysis = self._analyze_block_page(resp)
                    if block_analysis:
                        self.block_page_analysis = block_analysis
                        block_page_found = True

                    # 检测 WAF 特征
                    header_sigs = self._detect_by_headers(resp)
                    resp_sigs = self._detect_by_response(resp)
                    status_sigs = self._detect_by_status(resp)

                    for sig in header_sigs + resp_sigs + status_sigs:
                        if sig not in all_signatures:
                            all_signatures.append(sig)

                    print(f"  [拦截] {payload} -> {resp.status_code}")

                elif resp.status_code == 200:
                    # 200 但内容可能是拦截页
                    block_analysis = self._analyze_block_page(resp)
                    if block_analysis:
                        self.block_page_analysis = block_analysis
                        block_page_found = True
                        print(f"  [拦截页] {payload} -> {resp.status_code} (伪装 200)")

                # 延迟避免被限速
                time.sleep(0.3)

            except requests.exceptions.Timeout:
                print(f"  [超时] {payload}")
            except Exception as e:
                print(f"  [错误] {payload}: {e}")

        # 3. 识别 WAF
        if all_signatures or block_page_found:
            self.waf_detected = True
            waf_type, waf_name, confidence = self._identify_waf(all_signatures)
            self.waf_type = waf_type
            self.waf_name = waf_name
            self.confidence = confidence
        else:
            self.waf_detected = False
            self.waf_type = ""
            self.waf_name = ""
            self.confidence = "low"

        # 4. 获取绕过建议
        bypass_suggestions = self._get_bypass_suggestions(self.waf_name)

        duration = round(time.time() - start_time, 2)

        # 构建结果
        result = {
            "waf_detected": self.waf_detected,
            "waf_type": self.waf_type,
            "waf_name": self.waf_name,
            "confidence": self.confidence,
            "details": {
                "detection_method": "header_analysis_and_payload_testing",
                "matched_signatures": all_signatures,
                "response_headers": dict(normal_resp.headers) if 'normal_resp' in dir() else {},
                "block_page_analysis": self.block_page_analysis,
            },
            "bypass_suggestions": bypass_suggestions,
            "summary": {
                "tests_performed": tests_performed,
                "waf_detected": self.waf_detected,
                "duration_seconds": duration,
            },
        }

        return result


def main():
    """主入口"""
    input_path = "/input/input.json"
    output_path = "/output/results.json"

    try:
        with open(input_path, "r", encoding="utf-8") as f:
            config = json.load(f)

        if "target_url" not in config:
            raise ValueError("缺少必填字段: target_url")

        detector = WAFDetector(config)
        results = detector.detect()

        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(results, f, ensure_ascii=False, indent=2)

        summary = results["summary"]
        print(f"\n[完成] WAF 检测完成")
        print(f"  - WAF 检测: {'是' if results['waf_detected'] else '否'}")
        if results["waf_detected"]:
            print(f"  - WAF 类型: {results['waf_name']} ({results['waf_type']})")
            print(f"  - 置信度: {results['confidence']}")
            print(f"  - 绕过建议: {len(results['bypass_suggestions'])} 条")
        print(f"  - 测试次数: {summary['tests_performed']}")
        print(f"  - 耗时: {summary['duration_seconds']} 秒")

        sys.exit(0)

    except FileNotFoundError:
        print(f"[错误] 输入文件不存在: {input_path}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"[错误] JSON 解析失败: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"[错误] 检测过程异常: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
